name: helloworld-python app docker build
on: [push]
jobs:
  Check-and-build-Hellowrld-python:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository code
      uses: actions/checkout@v3
    - name: hello world
      run: |
        docker build -t helloworld-python-app .
    - name: Azure container scan
      uses: Azure/container-scan@v0
      with:
        image-name: helloworld-python-app
    - name: Connect to ACR
      uses: Azure/docker-login@v1
      with:
        login-server: acrue19.azurecr.io
        username: ${{ secrets.ACR_USERNAME }}
        password: ${{ secrets.ACR_PASSWORD }}
    - run: docker tag helloworld-python-app acrue19.azurecr.io/helloworld-python-app
    - run: docker push acrue19.azurecr.io/helloworld-python-app
