name: Helloworld-python app docker build
on: [push]
jobs:
  Check-and-build-Hellowrld-python:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository code
      uses: actions/checkout@v3
    - name: Hello world
      run: |
        docker build -t Helloworld-python-app .
